name: deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List contents of the repository
        run: ls -l
